-- Add up migration script here
CREATE TABLE color (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
	fallback TEXT NOT NULL
);

CREATE TABLE course (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
	color INTEGER NOT NULL,
	FOREIGN KEY(color) REFERENCES color(id)
);

CREATE TABLE category (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
	color INTEGER NOT NULL,
	FOREIGN KEY(color) REFERENCES color(id)
);

CREATE TABLE state (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
	color INTEGER NOT NULL,
	FOREIGN KEY(color) REFERENCES color(id)
);


CREATE TABLE time (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    start DATETIME NOT NULL,
	end DATETIME
);

CREATE TABLE task (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
	category INTEGER NOT NULL,
	course INTEGER,
	time INTEGER,
	state INTEGER,
	parent INTEGER,
	FOREIGN KEY(course) REFERENCES course(id),
	FOREIGN KEY(category) REFERENCES category(id),
	FOREIGN KEY(time) REFERENCES time(id),
	FOREIGN KEY(state) REFERENCES state(id),
	FOREIGN KEY(parent) REFERENCES task(id)
);
