[package]
name = "db-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.38"
syn = {version = "2.0.98", features = ["extra-traits", "full"]}
proc-macro2 = "1.0.93"
heck = "0.5.0"

[lib]
proc-macro = true
